services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # environment: 
    #   - NODE_ENV=${NODE_ENV}
    #   - PUBLIC_DATA_PORTAL_API_KEY_DECODING=${PUBLIC_DATA_PORTAL_API_KEY_DECODING}
    #   - PUBLIC_DATA_PORTAL_API_KEY_ENCODING=${PUBLIC_DATA_PORTAL_API_KEY_ENCODING}
    #   - OPENAI_API_KEY=${OPENAI_API_KEY}
    #   - DATABASE_USER=${DATABASE_USER}
    #   - DATABASE_PWD=${DATABASE_PWD}
    #   - DATABASE_SCHEMA=${DATABASE_SCHEMA}
    #   - DATABASE_HOST=${DATABASE_HOST}
    env_file:
      - .env.production.local
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3